### PR TITLE
Readjoiner output in GFA format

### PR DESCRIPTION
**Pull request by ggonnella**
Support output of Readjoiner in GFA format

### CODE REVIEW

**Comment by satta** [comment]
Looks good, but I wonder why there's no reference counting when holding references to Encseqs etc. (e.g. `gt_encseq_ref()`/`gt_encseq_delete()`/`gt_file_ref()`/`gt_file_delete()`?

**Comment by ggonnella** [comment]
I always use only one encseq and one file.

**Comment by satta** [comment]
Fair enough, given that this is meant for internal use. I was just wondering -- at the moment one could delete an encseq while it's still being used by a GtGfaWriter.

**Comment by ggonnella** [comment]
How would one avoid it using the system you mentioned before?

**Comment by ggonnella** [comment]
The GtGfaWriter is meant for internal use.

**Comment by satta** [comment]
By using ` gw->encseq = gt_encseq_ref(encseq);` in `gt_gfa_writer_new()` (and `gt_encseq_delete()` in  `gt_gfa_writer_delete()`)...

**Comment by ggonnella** [comment]
That seems very easy to implement, and I have nothing against it. I change it so.

**Comment by ggonnella** [comment]
However, for file is no problem, but for encseq, it discards the const qualifier. Is that really better (considered that encseq is only read here)?

**Pull request merged**
