### PR TITLE
make -contigs the default for gt seqstat

### LINKED ISSUE #610: gt seqstat produces no output by default
Perhaps `-contigs` should be the default behaviour?
```
~/w/pgmtdna git:master ❯❯❯ printf ">1\nACGT\n" >foo.fa
~/w/pgmtdna git:master ❯❯❯ gt seqstat foo.fa
~/w/pgmtdna git:master ❯❯❯
```

### PR DESCRIPTION
**Pull request by satta**
Closes #610.

### CODE REVIEW

**Comment by gordon** [comment]
This changes default behaviour. Now `-contigs` has to be disabled with `-contigs no`. Are you sure you want to do this?

**Comment by satta** [comment]
Since `gt seqstat` otherwise would not have printed anything, I think that the only case where this would impact existing workflows is when another option is chosen. The only other option outputting something is `-distlen`, and it creates output for which the output of `-contigs` would be a comment (with a `#` prefix). So I did not consider this a major impact.

**Comment by gordon** [comment]
OK, good point.

**Comment by sjackman** [comment]
Thanks!

**Pull request merged**
