### PR TITLE
Sk apply greedy and xdrop extensions for reverse and query matching

### PR DESCRIPTION
**Pull request by stefan-kurtz**
In additionen to the code related to xdrop/greedy extensions, an implementation of a linear space
alignment method using a diagonal band were added and the interface of the functions related to linear space alignment were unified.

### CODE REVIEW

**Comment by Garonenur** [comment]
would it be possible to squash those 191 commits so every new file added is just one commit?

**Comment by satta** [comment]
I have only reviewed the code in `core/` and `tools/` due to the sheer size of this PR. OK from my point of view, with a few typos etc. I might send a separate PR for later.
In general, I'm not a big fan of library functions calling `exit()` like `gt_alignment_check_match()` but as they are not part of an `_api.h` header I guess that's OK.
Does anyone else want to take a look?

**Comment by stefan-kurtz** [comment]
I have pushed a new commit which replaces the exit by an assertion. That 
is hopefully better. See also the comment
of the commit.

On 10/07/2015 12:26 PM, Sascha Steinbiss wrote:
>
> I have only reviewed the code in |core/| and |tools/| due to the sheer 
> size of this PR. OK from my point of view, with a few typos etc. I 
> might send a separate PR for later.
> In general, I'm not a big fan of library functions calling |exit()| 
> like |gt_alignment_check_match()| but as they are not part of an 
> |_api.h| header I guess that's OK.
> Does anyone else want to take a look?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genometools/genometools/pull/668#issuecomment-146145908>.
>


-- 
Prof. Dr. Stefan Kurtz
Zentrum fuer Bioinformatik
Universitaet Hamburg
Bundesstrasse 43
20146 Hamburg
Germany

Email:  kurtz@zbh.uni-hamburg.de
URL:    http://www.zbh.uni-hamburg.de/kurtz
Phone:  +49 (40) 42838 7311
FAX:    +49 (40) 42838 7312

**Comment by satta** [comment]
Well, the idea is to have it return a failure/success value that allows the caller to determine the error state and let the caller handle it, e.g. if someone want to use the check functionality in a graphical tool, one would rather want to display an error popup than to quit the entire program...

**Comment by stefan-kurtz** [comment]
On 10/08/2015 11:52 AM, Sascha Steinbiss wrote:
>
> Well, the idea is to have it return a failure/success value that 
> allows the caller to determine the error state and let the caller 
> handle it, e.g. if someone want to use the check functionality in a 
> graphical tool, one would rather want to display an error popup than 
> to quit the entire program...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genometools/genometools/pull/668#issuecomment-146478020>.
>
Hi Sascha,

the function was designed to be used for cases where other parts of the 
code produce invalid alignments, due to programming
errors. In such cases I consider that assertions are okay. Nevertheless, 
I have now added an error object and return codes
which allows
that the function is called for applications as you mentioned. But if 
the pointer to the error object is NULL, the
function behaves as before, because I do not want to thread an error 
object through several functions which display alignments.

Hope this is now okay. Bye, Stefan

-- 
Prof. Dr. Stefan Kurtz
Zentrum fuer Bioinformatik
Universitaet Hamburg
Bundesstrasse 43
20146 Hamburg
Germany

Email:  kurtz@zbh.uni-hamburg.de
URL:    http://www.zbh.uni-hamburg.de/kurtz
Phone:  +49 (40) 42838 7311
FAX:    +49 (40) 42838 7312

**Comment by gordon** [comment]
@stefan-kurtz: If possible, please send smaller and more frequent pull requests. Pull requests of this size are pretty much impossible to review.

**Pull request merged**
