### PR TITLE
gtgo: add some bindings for GtFeatureIndex

### PR DESCRIPTION
**Pull request by gordon**

### CODE REVIEW

**Comment by gordon** [comment]
I added more commits, now all bindings should be there which are necessary to reimplement the CGI scripts in Go.

**Comment by satta** [comment]
Very cool, and really clean to implement using cgo. That's where the design pays off! :)

I wonder though: Do we need to also make this work on systems that do not have Cairo? IIRC one can use build constraints to selectively enable/disable cgo directives, so one might want to have a `cairo`  (or `no-cairo`!) tag that one needs to pass in the `go build -tags` call to select this capability? Just an idea...

**Comment by gordon** [comment]
> Very cool, and really clean to implement using cgo. That's where the design pays off! :)

Yes, it really helped that we standardized a lot on how we wrote everything. That made it really easy to write the bindings.
And having the `_delete()` functions called by with `runtime.SetFinalizer()` is really neat, too.


> I wonder though: Do we need to also make this work on systems that do not have Cairo? IIRC one can use build constraints to selectively enable/disable cgo directives (https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command), so one might want to have a `cairo` (or `no-cairo`!) tag that one needs to pass in the `go build -tags` call to select this capability? Just an idea...

I tried to get around that for a minimal version, but just added it. It's the proper approach, of course.

**Comment by satta** [comment]
Merged, thanks for that! 👍

**Pull request merged**
