### PR TITLE
Sk Improve default parameters and fixed bugs for greedy/xdrop extensions

### PR DESCRIPTION
**Pull request by stefan-kurtz**

### CODE REVIEW

**Comment by satta** [comment]
Hmm, this seems to change the command line interface of the `gt repfind` tool... this might break user scripts?

**Comment by stefan-kurtz** [comment]
Hi Sascha,

good point. So I have added back the option -err and declared it as 
developer option.
I have additionally specified the range of possible values (which was 
not done earlier
versions of the code.) The change was just pushed. A far as I see, I do not
need another pull request.

Bye, Stefan

On 07/29/2015 18:00 , Sascha Steinbiss wrote:
>
> Hmm, this seems to change the command line interface of the |gt 
> repfind| tool... this might break user scripts?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genometools/genometools/pull/635#issuecomment-125998897>.
>


-- 
Prof. Dr. Stefan Kurtz
Zentrum fuer Bioinformatik
Universitaet Hamburg
Bundesstrasse 43
20146 Hamburg
Germany

Email:  kurtz@zbh.uni-hamburg.de
URL:    http://www.zbh.uni-hamburg.de/kurtz
Phone:  +49 (40) 42838 7311
FAX:    +49 (40) 42838 7312

**Comment by satta** [comment]
Thanks! Also, `-extendgreedy` and `-extendxdrop` used to be boolean options and now take an integer? I guess this could also lead to errors when passed `true` or `false`, `yes` or `no`...

**Comment by stefan-kurtz** [comment]
Hi Sascha,

it was not possible to pass true or false/yes or no as arguments for 
these options. It was
also not document that these arguments are possible. So the
additional optional arguments should no break anything.

Bye, Stefan

On 07/29/2015 21:04 , Sascha Steinbiss wrote:
>
> Thanks! Also, |-extendgreedy| and |-extendxdrop| used to be boolean 
> options and now take an integer? I guess this could also lead to 
> errors when passed |true| or |false|, |yes| or |no|...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/genometools/genometools/pull/635#issuecomment-126060602>.
>


-- 
Prof. Dr. Stefan Kurtz
Zentrum fuer Bioinformatik
Universitaet Hamburg
Bundesstrasse 43
20146 Hamburg
Germany

Email:  kurtz@zbh.uni-hamburg.de
URL:    http://www.zbh.uni-hamburg.de/kurtz
Phone:  +49 (40) 42838 7311
FAX:    +49 (40) 42838 7312

**Comment by satta** [comment]
I see. With this in in mind, if the user passes `-extendgreedy` and `-extendxdrop` without arguments (as you would have done before), the default numeric value seems to be used. So I guess the API is still OK.

**Pull request merged**
