### PR TITLE
fix minor spelling issues

### PR DESCRIPTION
**Pull request by satta**
Just Lintian things.

### CODE REVIEW

**Comment by Garonenur** [comment]
not quite sure why this test should fail. Will you yourself have a look?

**Comment by satta** [comment]
Probably some quirk in the test container or a remaining race condition? It looks too isolated to be a systematic thing. I get some of these every once in a while.

**Comment by Garonenur** [comment]
fine by me to restart the test then. It is pretty hard to recreate those errors anyway.

**Comment by satta** [comment]
OK, cool. Greetings from Lyngby!

**Pull request merged**
