### PR TITLE
fastawidth: Document that 0 is unlimited

### PR DESCRIPTION
**Pull request by sjackman**

### CODE REVIEW

**Comment by Garonenur** [comment]
thank you, and with that, welcome as one of the maintainers of genometools :)

**Comment by sjackman** [comment]
Thanks, Dirk. It's that easy, eh? Why do I feel like I've just been conscripted to the infantry?

**Comment by Garonenur** [comment]
no obligations :), but if you want to, read the "rules" that are linked in our readme under contribution.

**Comment by gordon** [comment]
@sjackman: Welcome! And no pressure ;-)

Our development contract: http://genometools.org/contract.html

**Pull request merged**
