### PR TITLE
add build status badge to README.md

### PR DESCRIPTION
**Pull request by gordon**

### CODE REVIEW

**Comment by standage** [comment]
Running integration tests for commits like this (commits that don't change any source code) isn't necessary. If you add `[skip ci]` to a commit message, Travis will not run tests for that commit. I do this for my repos when I edit the README or other files that don't affect the actual source code.

Something to consider.

**Comment by satta** [comment]
Nice to learn that! Thanks Daniel.

**Comment by Garonenur** [comment]
:+1: @standage nice to know!

**Comment by gordon** [comment]
Thanks for the info!

**Pull request merged**
