### PR TITLE
update unit test for GtPriorityQueue

### PR DESCRIPTION
**Pull request by satta**
checks the cases in #714, also removes `exit` calls to bring the test in line with the rest of the GenomeTools style

### CODE REVIEW

**Comment by gordon** [comment]
`static` functions don't need the `gt_` prefix, because they are not exported.

**Comment by satta** [comment]
I know... still I like to have functions gt-prefixed for compiling with `amalgamation=yes` to avoid name clashes with future functions.

**Comment by Garonenur** [comment]
```gt_``` wouldn't help you with amalgamation, unless we amalgamate external stuff, too?

**Comment by satta** [comment]
That's a different story. I was more thinking about generic function names like `cmpUlong` which might be reimplemented as a static accessory function in a different .c file, clashing when they get compiled together. `gt_` alone wouldn't help there, that's why I am in favour of unique module prefixes.

**Pull request merged**
