### PR TITLE
clean (gt)testdata

### PR DESCRIPTION
**Pull request by joergi-w**
**Issue**: *make test* produces several index files in testdata and gttestdata (sub-)directories. 
When threaded tests produce the same files simultaneously, there can occur write conflicts. 
[testdata_modifications.txt](https://github.com/genometools/genometools/files/5113/testdata_modifications.txt)
**Solution**: Intermediate files are created only in the test's working directory.

### CODE REVIEW

**Comment by satta** [comment]
Cool, thanks @joergi-w! I wonder whether it could make sense to have the staging of local file copies done as part of the test suite definition, so it is not overlooked as easily (and it would also allow to clean up the local indexes afterwards). E.g. like:

```Ruby
Name "gt extractfeat -seqfile test 1"
Keywords "gt_extractfeat"
UsesFiles ["#{$testdata}gt_extractfeat_succ_1.fas"]
Test do
  run_test "#{$bin}gt extractfeat -type gene " \
    "-seqfile gt_extractfeat_succ_1.fas " \
    "-matchdesc #{$testdata}gt_extractfeat_succ_1.gff3"
  run "diff #{last_stdout} #{$testdata}gt_extractfeat_succ_1.out"
end
```
The cleanup step for this test could then use the information used in the `UsesFiles` annotation to delete the corresponding file in the test directory after a successful run.

**Comment by Garonenur** [comment]
we should also put up an issue that the default behavior of future tools should be different and all implicit created files should be created in the current working directory. Therefore eliminating the need for this. Although this would either need a default filename, or basename parsing.

**Comment by gordon** [comment]
I don't think that creating files in the current working directory is the correct solution. Then you would end up with intermediate files all over the place. In my opinion there are two possible solutions to the general problem:

- Always create intermediate files manually. Vmatch uses that approach. I find it to bothersome for the user with workflows where you have to create many intermediate files.

- The approach I use in GenomeThreader is twofold: Use `gt_file_is_newer()` to determine if an intermediate file has to be recreated (i.e., the original file changed) and to use file locking to make sure that two process do not write an intermediate file at the same time. Unless you are on a messed up NFS installation file locking worked great in practice so far.

When two processes are trying to create the same index file it is important that the second one uses the index the first one wrote and doesn't recreate it once again.

See for example the usage of `gt_fa_lock_exclusive()`, `gt_fa_lock_shared()`, and `gt_fa_unlock()` in [src/core/md5_tab.c](https://github.com/genometools/genometools/blob/master/src/core/md5_tab.c)

Therefore, it seems to me that we do not have a problem with the testsuite, but we have problems with some of the tools. In my opinion the problem should be fixed there. Otherwise the user will end up with the same problem we have with the testsuite now. Or he will clutter his file tree with intermediate files.

**Comment by satta** [comment]
I agree that there should no files be created in the CWD. That might not even always be writable!
As far as file locking goes, this seems to be the only serious solution, but I wasn't sure how portable it is and how well it works (see http://0pointer.de/blog/projects/locking.html). But if it solves our problem in most cases for the GtBioseq, so be it.

**Comment by Garonenur** [comment]
OK, I see your point there. Only that the directory where the input is read from might not be writable for the user either, therefore preventing creating the intermediate file(s) there, too.

And yes, this problem should be fixed within the tools, and we should try to enforce locking in future tools, but @joergi-w who did this PR here for us wouldn't have the time to change the behavior of all our tools. Therefore we (that is @stefan-kurtz and me mainly) asked him to implement this work-around so the tests stop failing from this mutual file access.

I think therefore it is OK to merge this, and we should maybe create an issue to address this problem, and maybe someone has time to got to this.

**Comment by joergi-w** [comment]
I have changed the path of the GtCondenseq test back to gttestdata/condenseq. So the gttestdata repository should be updated to pass the test (see comment by @Garonenur). 

For the current solution I like the *UsesFiles* attribute that @satta suggested. I will meet @stefan-kurtz or @Garonenur tomorrow to talk about how to set this up.

**Comment by Garonenur** [comment]
the gttestdata was updatet, so both gt and gttestdata should be pulled to make sure this works.

**Pull request merged**
