### PR TITLE
fixes #815

### LINKED ISSUE #815: Failing MD5 test
## Problem description

Travis fails test 1068 with seed 1209700457

```
FAILING test, output of testsuite/stest_testsuite/test1068/stderr_1
/home/travis/build/genometools/genometools/bin/gt: error: could not execute script ...ls/genometools/src/external/md5-1.1.2/tests/test.lua:78: assertion failed!
FAILING test, output of stest_error
Test 1068 'MD5 library': failed:
unexpected return code: 1 != 0:
/home/travis/build/genometools/genometools/testsuite/stest.rb:286:in `run'
/home/travis/build/genometools/genometools/testsuite/stest.rb:449:in `run'
testsuite.rb:98:in `run_test'
/home/travis/build/genometools/genometools/testsuite/gt_scripts_include.rb:137:in `block in <top (required)>'
/home/travis/build/genometools/genometools/testsuite/stest.rb:176:in `block in test'
/home/travis/build/genometools/genometools/testsuite/stest.rb:165:in `fork'
/home/travis/build/genometools/genometools/testsuite/stest.rb:165:in `test'
/home/travis/build/genometools/genometools/testsuite/stest.rb:120:in `process'
/home/travis/build/genometools/genometools/testsuite/stest.rb:34:in `block (2 levels) in run'
     [ problem: unexpected return code: 1 != 0
       in: /home/travis/build/genometools/genometools/testsuite/stest_testsuite/test1068 ]
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?

1.5.9, latest git (bbd497d)

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.

`amalgamation=yes`

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?

Travis Linux test VM

### PR DESCRIPTION
**Pull request by Garonenur**
update to the external source for the lua md5 library

### CODE REVIEW

**Comment by Garonenur** [comment]
closes #815

**Comment by satta** [comment]
Hmm... IMHO it might be better to rename the directory to match the new version (i.e. ` src/external/md5-1.2`)?

**Comment by gordon** [comment]
Makes sense, if that is the version we use now.

**Comment by Garonenur** [comment]
the readme in the md5-repo still says 1.1.2 were do you get the 1.2 from?

**Comment by satta** [comment]
https://github.com/keplerproject/md5/releases and also https://github.com/genometools/genometools/pull/819/commits/a84d92ab4edbba144f3a9b5c9b310e18d0905798#diff-d65dd24d896c9acdfe2508e90cbfdbcfR100

I think the README just wasn't updated...

**Comment by Garonenur** [comment]
OK. I will rename it and create a pull request for his readme.

**Comment by satta** [comment]
Excellent.  Will merge once Travis completes.

**Pull request merged**
