### PR TITLE
make `make` option more consistent with other opts

### PR DESCRIPTION
**Pull request by gordon**

### CODE REVIEW

**Comment by teythoon** [comment]
Well, naming that 'V' was a conscious decision.  This is what automake uses:

https://www.gnu.org/software/automake/manual/html_node/Automake-Silent-Rules.html

**Comment by gordon** [comment]
Well, we don't use automake and that was a conscious decision, too.

**Comment by teythoon** [comment]
> Well, we don't use automake and that was a conscious decision, too.

So I gather you don't like automake.  Fine, there are other build systems to choose from.  Instead, you went with no build system at all.  If you look at your Makefile today, do you still think this was a good call?

I'm not trolling, I'm really curious what you think.  Because from my perspective your solution is messy and inflexible, and missing important features.  And I'd much rather have used any proper build system, even if it was unfamiliar to me.

**Comment by satta** [comment]
I guess our approach was born when GenomeTools was substantially smaller and largely self-dependent, not relying on many external dependencies. Things like samtools and friends got sucked into the codebase when the need for them arose.
I agree that our Makefile as it is at the moment is quite arcane and probably not particularly community-maintainable. On the other hand, we do have a few peculiarities (embedded library code, amalgamation, ...) that I'm not sure whether they can be implemented 'out of the box' with build systems like autotools. I'd be curious to hear what features you miss in particular, and what alternatives you would propose. I'd also like to hear @gordon's comments ;)

**Comment by teythoon** [comment]
Well, I suggest to use any build system.  I'm only familiar with the GNU build system, but from gordons snotty response I gather that he doesn't like that.

What I miss most is a proper configuration phase.  E.g. by accident I did 'make some=option', then the build broke at some point, I fixed that, and did 'make'.  But that didn't continue the previously build properly, instead building whatever was left without the options.  Oops.

Also, for every library that you do use, one should have the option to point the build system to the location of the library.  pkg-config helps somewhat, but with the GNU build system you'd get e.g. --with-sqlite3=/some/path for free.

The configuration phase can also be used to detect and handle differences between platforms.  This makes cross-compilation much easier.

A proper build system supports out-of-tree builds, so you can have different builds sharing the same source tree.

I don't agree with your need for embedding libraries, and amalgamation afaics only serves others that want to use libgenometools without properly building it as a shared library and linking to it.

**Comment by gordon** [comment]
I think to have any meaningful discussion about the question what a good build system for GenomeTools is we have to look at the _environment_ GenomeTools is used in and about the _requirements_ of a build system in such an environment.

GenomeTools is scientific software in the realm of bioinformatics. In my experience the typical academic environment in bioinformatcs looks somewhat like this:

- Linux or Mac machines, often not properly updated
- user doesn't have root
- it is not trivial to have third party packages installed
- the user is often not a computer scientist

The situation on academic compute clusters is often even worse. When GenomeTools was started **ten years** ago I had the following requirements:

- _portable_ binaries. In the environment described above that means _statically_  _linked_ binaries (only link dynamically against an *old* version of glibc). You cannot assume anything about installed libraries. This is the primary way of distributing it.
- an easy way to build GenomeTools from source. This is the secondary way of distributing it.
- a build system which is convenient during development
- a build system which allows cross-compilation

For the source code you need an installed C compiler. For the build system I had the the following choices:

- a portable shell script
- GNU make (it is reasonable to assume GNU make is installed on any system with a C compiler which we encountered _in_ _practice_)
- autotools

**Everything** else is another dependency and therefore violates the requirements. CMake? Not installed everywhere. SCons? Requires Python. And so on...

A shells script works for simple projects, but I wanted something which only rebuilds the necessary files during development. That leave me with GNU make and autotools. With GNU make you can build the entire project (with all dependencies) from a single Makefile with a single tool. Even after nearly thirty years of development the GNU make manual is a little over 200 pages. It is a one time investment to learn it. It is very stable.  In fact, I can still build the first commit c6f25e125a1e51e11f56a79020600e0f1f18e306 without any changes on my Linux system.

Autotools on the other hand is a beast of enormous complexity. Just look at the flow diagram on [Wikipedia](https://en.wikipedia.org/wiki/GNU_build_system). I like _simple_ solutions and I was never able to understand Autotools completely (and I tried).
Therefore the I chose GNU make at the time. GNU make also has the advantage that I can build the entire project with a single call. Autotools requires at least two steps. 

A "proper configuration phase" means I have to rerun `configure` if I want to compile with different options. With our setup it's a simple:

```
make clean
make opt=no
```

for example. Install ccache and you can rebuild very quickly on a modern machine with SSD.

> If you look at your Makefile today, do you still think this was a good call?

Yes, because it meets the requirements (and I don't think they have changed).
Does it look pretty? Not anymore. It grew some wards in the last ten years, growing from 81 lines to 1179 (with at least 8 different people touching it). But it it works in practice. So well in fact, that I can cross-compile nine different [GenomeThreader](http://genomethreader.org/) distributions with it from a single shell script (GenomeThreader depends on GenomeTools). And the resulting binaries run pratically everywhere.

Debian packages are nice (and I'm grateful that @satta did the necessary work and maintains them), but they are just not a major requirement. They are more of a nice third way of distribution. Because: a.) some users cannot install them (see requirements). b.) the software sometimes moves faster than the distributions catch up (then we are back to binary or source distributions).

@teythoon: Calling my previous response "snotty" doesn't contribute to an objective discussion. To be honest, your writing style strikes me as a bit condescending as well.

I suggest that instead of using terms like "should" and "is generally frowned upon" you argue from a perspective of: What problem are you trying to solve? Does the alternative solution solve the problem while still meeting the requirements? If you do not like the requirements then please argue why they do not apply anymore.

And if you have a problem to solve, then please be ready to do the necessary work to bring the alternative solution to the same stage at which we are now: A solution that works very well in practice. Thanks!

**Comment by gordon** [comment]
I forgot to mention: Our current solution also allows to build an "amalgamation" of the code (with `amalgamation=yes`). The idea comes from [SQLite](https://www.sqlite.org/) and last time I checked it leads to a 10% speed-up (the compiler can optimize all code at the same time). 

This is something which is quite important for the CPU intensive tasks in bioinformatics.

**Comment by teythoon** [comment]
> Calling my previous response "snotty" doesn't contribute to an objective discussion. To be honest, your writing style strikes me as a bit condescending as well.

Fair enough, I'm sorry.

> I suggest that instead of using terms like "should" and "is generally frowned upon" you argue from a perspective of: What problem are you trying to solve? Does the alternative solution solve the problem while still meeting the requirements? If you do not like the requirements then please argue why they do not apply anymore.

I was trying to package GenomeTools for Guix.  You should check Guix out, it is a functional package manager that can be installed on top of other distributions without the need to be root.

> And if you have a problem to solve, then please be ready to do the necessary work to bring the alternative solution to the same stage at which we are now: A solution that works very well in practice. Thanks!

I have spent considerable time on massaging your "build system" into shape so that GenomeTools can be packaged cleanly.  This is a problem that projects following common software development best practices simply do not have.  So suggesting that I'm not willing to invest time, or that I'm unwilling to work with whatever solution is in place seems hardly fair.

**Comment by Garonenur** [comment]
I am going to guess that the discussion within this pull request does non invalidate said PR and merge it.
Maybe this should then be continued to be discussed within an extra issue.

**Comment by gordon** [comment]
> I was trying to package GenomeTools for Guix. You should check Guix out, it is a functional package manager that can be installed on top of other distributions without the need to be root.

Thanks for the pointer, I will check it out. Also not trying to troll, but curious: What problem does that solve for the user?

>  So suggesting that I'm not willing to invest time, or that I'm unwilling to work with whatever solution is in place seems hardly fair.

I wasn't. Sorry if you got the impression.

Please let's follow @Garonenur's lead and continue the disussion in a new issue. I created issue #752 for that reason.

**Pull request merged**
