### PR TITLE
gt-users is defunct, use GitHub to report bugs

### PR DESCRIPTION
**Pull request by gordon**

### CODE REVIEW

**Comment by satta** [comment]
I think it's a good idea to suggest that users open new issues here on GitHub. 
However, I wouldn't write off the mailing list completely -- I know for a fact that there are still people out there (e.g. managing software installations on compute farms) that are subscribed to (potentially many) mailing lists like ours to be notified of new version updates. So I would still be i favour of at least keeping the part about sending release emails. What do you think?

**Comment by gordon** [comment]
OK, it makes sense to keep sending out notification email. But I don't want to maintain a mailing list for that myself. An alternative would be to have something like https://mailchimp.com/ for release announcement, but that usually costs money after a while.

I found https://about.sibbell.com/ which can be used to get release notifications for projects on GitHub. What about pointing people to that?

**Comment by satta** [comment]
I use that myself as well. However, with the free version you can only get release notifications for _all_ repos starred in your GitHub account... but I guess that's still fine. Also, we should probably send out a closing notice to the mailing list if it is to be discontinued.

**Comment by gordon** [comment]
I sent out the discontinuation mail. @satta Should we do another release to make sure the issue tracker address and bug fixes are propagated upstream?

**Comment by satta** [comment]
> I sent out the discontinuation mail.

Great! Not sure why I didn't find one in my inbox though...

> @satta Should we do another release to make sure the issue tracker address and bug fixes are propagated upstream?

I guess that's a good idea. Can you, should I?

**Comment by gordon** [comment]
Darn, delivery failed. Sorry, there is nothing I can do about that now without major work.

Could you do the release? You have to do the Debian part anyway... Should we merge https://github.com/genometools/genometools/pull/872 beforehand?

**Comment by satta** [comment]
> Could you do the release? You have to do the Debian part anyway... 

Sure, I'll see to it tomorrow. 

> Should we merge #872 beforehand?

I was initially going to wait for someone to take a closer look. But I'm fairly sure it does the right thing ;)

**Comment by gordon** [comment]
Thanks! OK, I went ahead and merged it ;)

**Comment by satta** [comment]
Uploaded most binaries and the source tarball. Will try to work on the Debian packages in my way to DebConf and build the missing Windows binaries when I find some time.

**Comment by satta** [comment]
All done!

**Comment by gordon** [comment]
Thanks! Should I start the RELEASE process then or are you doing it?

**Comment by satta** [comment]
That should basically all be done already, I've pushed tags, incremented the version number, uploaded all binaries and source tarball, and the new Debian packages are in unstable. Did I miss anything (apart from the email)?

**Comment by gordon** [comment]
Ah, no. That seems fine. I was expecting a pull request and didn't check the commit history ;-)

**Pull request merged**
